version: '3'

services:
  redis:
    image: redis
    networks:
        - frontend
    deploy:
      replicas: 5
    command: redis-server --requirepass password
    ports:
      - "6379:6379"

  vizualizer:
    image: dockersamples/visualizer:stable
    networks:
        - frontend
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
        
networks:
  frontend: